### ISSUE TITLE
Weird behavior when working with a bool

### ISSUE THREAD

**Issue by akamud** [aritchie/settings#20]
If you are using a `bool` as a Setting, you can get a scenario with a weird behavior:

```C#
var firstExecution = Settings.Current.Get<bool>("First", true);
if (firstExecution)
    Settings.Current.SetDefault<bool>("First", false);
```

You will always get `firstExecution` as `true`. The culprit is this [line](https://github.com/aritchie/settings/blob/b5b1b22d210e3198832253f59f7ef98dff5aca6c/src/Acr.Settings.Interface/AbstractSettings.cs#L112), Acr.Settings removes the key instead of persisting it as `false`, because `false` is the default value for `bool`. I don't think this should happen, in fact, since we have a `Remove` method implemented, we should choose when to clear a key, and not have unexpected behavior inside the Set. 

What do you think?

**Comment by aritchie** [comment]
SetDefault will only set a key if the value isn't present in the dictionary.  You aren't using it appropriately.  Your test case is actually a contradiction of itself.  

With booleans, you shouldn't actually use SetDefault unless you are setting it to true from the beginning.  False will be the default return from Get anyhow.

**Comment by akamud** [comment]
I'm sorry, I actually pasted the wrong sample, this is the code I should have posted:

```C#
var firstExecution = Settings.Current.Get<bool>("First", true);
if (firstExecution)
    Settings.Current.Set<bool>("First", false);
```

**Comment by aritchie** [comment]
I've had a chance to think about this, but honestly, while this is mostly a defect, there are many reasons why I don't set the default values into the settings.  

The main reason is if you simply do Settings.Current.Set<bool>("First") - it will return false.  My best suggestion here (and possibly a better solution anyhow) is to use the following

`
var count = Settings.Current.Get("Count", 1); // or Settings.Current.Get<int>("Count");
Settings.Current.Set("Count", count + 1);
if (count == 1) 
{
// do something - you could even say for the 5th start, maybe you want an app review popup or something
}
`

**Comment by akamud** [comment]
The thing that bothers me is the fact that the `Set` method does more than I expect and clears a value. Is this really necessary?

**Comment by aritchie** [comment]
I really don't think I should have to explain myself for a decision as I'm the one doing the work.  Next time, if you feel something is bothering you, submit a PR with what you think the behavior should be that passes all of the unit tests within the project.

In the mean time, I have ironed this one out.

**Comment by akamud** [comment]
Look, if I ended up sounding harsh or something, I apologize, it definitely wasn't my intention. I thought we were constructively discussing something.

I have to disagree with you about not having to explain your decision, if you expect help from the community, then we have to discuss decisions in public so we can understand the meaning and improve.

I have contributed to dozens of open source projects and I maintain some myself, and opening a PR that changes existing behavior without first consulting the maintainers with an Issue is not a best practice. Changing existing behavior needs discussion, and I'm always glad when someone shows a way of improving open source projects.

So, thanks for taking the time creating the commit, but next time a "Ok, we can change the behavior, feel free to send a PR if you have the time" would suffice. Let's make the open source community better and more welcoming ;)

**Comment by aritchie** [comment]
I appreciate you taking the time to file the issue.  Yours was better explained than most I usually receive.  However, I find this comment to be really unfair.  My comment about submitting a PR was not unfair by any means.  I didn't deny your request (or I would have closed the issue as not a bug), I even acknowledged the issue with a somewhat vague explanation of why I don't just change the behavior but I did take some time to "explain myself".  In return, you didn't says "thanks" or "ok".  You gave a one line, non-constructive repeat of your initial request with a fairly disrespectful "Is this really necessary" to which I had already stated it had potential issues.

Also….no offense, but no… I don't have explain myself.  I certainly appreciate that the community gets value out of my code, but at no time did I expect or even ask for help.  Again, I appreciate when it comes so long as it remains constructive and respectful.

Now with regards to "let's keep the open source welcoming".  I get on average 20 communications a day via multiple channels for different libraries.  Roughly 40-50% of these are requests for timelines, feature requests with hopes I can "do it soon", or swearing about at me about some issue or another.  I often have to repeat instructions that I've already taken the time document, etc.  While none of this is certainly your problem, I do find that non-maintainers throw this "unwelcoming" term around when they don't get their way.  "No", "this isn't something I want to do", or "submit a PR" is not being unwelcoming… it is simply that I don't work for the community and the community doesn't necessarily have to support the change they are purposing going forward…. The maintainer(s) do.  So….the welcoming aspect is jaded on me because it is often one sided especially when I take the time to fix an issue and I get a "thanks, but…" response.
