### ISSUE TITLE
V7.0.0 NuGet package does not work.

### ISSUE THREAD

**Issue by philmoz** [aritchie/settings#23]
Updating from the 6.0.1 version to 7.0.0 NuGet package breaks my projects.

In the PCL or .Net Standard library code the Acr.Settings namespace cannot be found.

Looking at the Assembly Browser shows that the PCL part of the package is empty in 7.0.0 (see attached screenshot). Tested in both a PCL library and .Net Standard library.

Using Visual Studio for Mac V7.1.5 (build 2).

<img width="1046" alt="screen shot 2017-10-04 at 8 26 13 am" src="https://user-images.githubusercontent.com/9474356/31150310-cec488dc-a8de-11e7-8fb7-721c6b358f15.png">

**Comment by ignasbagdonas** [comment]
Yes, for me the same problem. I had to downgrade to v6.
I looked at the code. Why Acr.Settings project is empty now?

**Comment by aritchie** [comment]
7.0.0 was released by accident.  I'll patch it in the next couple of days.  The issue is that "Acr.Settings.Interfaces" wasn't referenced by "Acr.Settings".  If you manually add it from the packages folder for now, things will work.

@ignasbagdonas It has always been this way.  Acr.Settings is the "bait" library that is "switched" by the platform version

**Comment by philmoz** [comment]
NuGet package 7.0.1 is still broken.
The 'Acr.Settings.Interface' namespace is now present; the 'Settings' property is missing.

**Comment by aritchie** [comment]
Just take a chill for now.  It is executing the wrong build script on one of my CI servers.  I will update this issue when I have a chance to resolve it

**Comment by aritchie** [comment]
This issue has been resolved on 7.0.2 and is available on nuget.
